#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: bionic-tiny
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  tag: #@ "{}:clusterbuilder-{}".format(data.values.kp_default_repository.name, "bionic-tiny")
  stack:
    name: bionic-tiny
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/java-native-image
    - group:
        - id: paketo-buildpacks/procfile

---
apiVersion: kpack.io/v1alpha2
kind: ClusterBuilder
metadata:
  name: bionic-base
spec:
  serviceAccountRef:
    name: kp-default-repository-serviceaccount
    namespace: kpack
  tag: #@ "{}:clusterbuilder-{}".format(data.values.kp_default_repository.name, "bionic-base")
  stack:
    name: bionic-base
    kind: ClusterStack
  store:
    name: default
    kind: ClusterStore
  order:
    - group:
        - id: paketo-buildpacks/dotnet-core
    - group:
        - id: paketo-buildpacks/nodejs
    - group:
        - id: paketo-buildpacks/go
    - group:
        - id: paketo-buildpacks/python
    - group:
        - id: paketo-buildpacks/nginx
    - group:
        - id: paketo-buildpacks/java-native-image
    - group:
        - id: paketo-buildpacks/java
    - group:
        - id: paketo-buildpacks/procfile
