#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: tiny
spec:
  id: "io.buildpacks.stacks.jammy.tiny"
  buildImage:
    image: paketobuildpacks/build-jammy-tiny:0.1.19
  runImage:
    image: paketobuildpacks/run-jammy-tiny:0.1.19

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: paketobuildpacks/build-jammy-base:0.1.18
  runImage:
    image: paketobuildpacks/run-jammy-base:0.1.18

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: default
spec:
  id: "io.buildpacks.stacks.jammy"
  buildImage:
    image: paketobuildpacks/build-jammy-base:0.1.18
  runImage:
    image: paketobuildpacks/run-jammy-base:0.1.18
