#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java:8.9.0
    - image: gcr.io/paketo-buildpacks/java-native-image:7.46.0
    - image: gcr.io/paketo-buildpacks/procfile:5.6.0
    - image: gcr.io/paketo-buildpacks/go:4.2.0
    - image: gcr.io/paketo-buildpacks/python:2.8.0
    - image: gcr.io/paketo-buildpacks/nodejs:1.3.1
    - image: gcr.io/paketo-buildpacks/nginx:0.12.2
    - image: gcr.io/paketo-buildpacks/dotnet-core:0.33.0
