#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStore
metadata:
  name: default
spec:
  sources:
    - image: gcr.io/paketo-buildpacks/java:8.6.0
    - image: gcr.io/paketo-buildpacks/java-native-image:7.44.1
    - image: gcr.io/paketo-buildpacks/procfile:5.5.0
    - image: gcr.io/paketo-buildpacks/go:4.0.1
    - image: gcr.io/paketo-buildpacks/python:2.7.1
    - image: gcr.io/paketo-buildpacks/nodejs:0.28.0
    - image: gcr.io/paketo-buildpacks/nginx:0.12.0
    - image: gcr.io/paketo-buildpacks/dotnet-core:0.28.0
