#@ load("@ytt:data", "data")
---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: tiny
spec:
  id: "io.paketo.stacks.tiny"
  buildImage:
    image: paketobuildpacks/build-bionic-tiny:1.3.99
  runImage:
    image: paketobuildpacks/run-bionic-tiny:1.3.99

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: base
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: paketobuildpacks/build-bionic-base:1.2.57
  runImage:
    image: paketobuildpacks/run-bionic-base:1.2.57

---
apiVersion: kpack.io/v1alpha2
kind: ClusterStack
metadata:
  name: default
spec:
  id: "io.buildpacks.stacks.bionic"
  buildImage:
    image: paketobuildpacks/build-bionic-base:1.2.57
  runImage:
    image: paketobuildpacks/run-bionic-base:1.2.57
