name: Test
on:
  - push

jobs:
  check-config:
    name: Check Configuration
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3.1.0

      - name: Set up Carvel
        uses: vmware-tanzu/carvel-setup-action@v1.1.1
        with:
          only: ytt
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Check configuration
        run: |
          make check
